#!/usr/bin/env bash
set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${REPO_ROOT}" || exit 1

if [[ ! -e "gen/active.env" ]]; then
    echo "default.env -> active.env"
    cp gen/default.env gen/active.env
else
    echo "active.env already configured"
fi
