#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DOTBOT_DIR="ext/dotbot"
DOTBOT_BIN="bin/dotbot"


cd "${BASEDIR}"
git submodule update --init --recursive 

CONFIG="install.conf.yaml"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
