#!/usr/bin/env bash
set -e

REPO_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cd "${REPO_ROOT}" || exit 1

DOTBOT_DIR="$REPO_ROOT/ext/dotbot"
DOTBOT_BIN="bin/dotbot"

git submodule update --init --recursive 

./bootstrap
./generate

CONFIG="$REPO_ROOT/etc/install.yml"
"${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${REPO_ROOT}" -c "${CONFIG}" "${@}"

if [ "$(uname)" = "Darwin" ]; then
    CONFIG_MAC="$REPO_ROOT/etc/install.mac.extra.yml"
    "${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${REPO_ROOT}" -c "${CONFIG_MAC}" "${@}"
fi
