#!/bin/bash

REPO_ROOT=$(realpath $(dirname "${BASH_SOURCE[0]}"))

# Previously ssh config was linked into here
# This seems to break some software, so I stopped doing it like this
if [ -L ~/.ssh/config ] && [[ "$(readlink ~/.ssh/config)" == "$REPO_ROOT"* ]]; then
    echo "Detected old symbolic link ~/.ssh/config, removing"
    rm ~/.ssh/config
fi
