#!/bin/bash
set -e

REPO_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cd "${REPO_ROOT}" || exit 1

. "bin/common"

log_info "update: repo root: $REPO_ROOT"

log_info "update: updating submodules"
git submodule foreach --recursive git pull --prune

log_info "update: fetching fzf bindings"
curl -fLo "$REPO_ROOT/etc/zsh/conf.d/fzf/completion.zsh" \
    https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh
curl -fLo "$REPO_ROOT/etc/zsh/conf.d/fzf/key-bindings.zsh" \
    https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh

log_ok "✅ update: done"
