#!/bin/bash
set -ex

REPO_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

git submodule foreach --recursive git pull --prune

curl -o "$REPO_ROOT/etc/zsh/conf.d/fzf/completion.zsh" https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh
curl -o "$REPO_ROOT/etc/zsh/conf.d/fzf/key-bindings.zsh" https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh
