#!/bin/bash

case $1 in

install-server)
    if [ "$EUID" -ne 0 ]
        then echo "Please run with sudo"
        exit
    fi

    cd /etc/wireguard

    umask 077
    wg-gen peer1
    wg-gen server
    ;;

list-pubkeys)
    echo Server:
    sudo cat /etc/wireguard/server_publickey
    echo
    echo Peer1:
    sudo cat /etc/wireguard/peer1_publickey
    ;;
*)
    echo "wireguard [install-server|list-pubkeys]"
    ;;
esac
