"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Author: Jacob Peyron <jacob.peyron@gmail.com>
"
" Source all the files
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

source ~/.dotfiles/etc/vim/vim.d/plugins.vim
source ~/.dotfiles/etc/vim/vim.d/general.vim
source ~/.dotfiles/etc/vim/vim.d/keymap.vim
source ~/.dotfiles/etc/vim/vim.d/platform.vim
