#!/bin/zsh
#
# .zlogin
# login -> desktop

readonly desktop=start-hyprland
#readonly desktop=tmux

start_tmux() {
    [[ $commands[tmux] ]] && [ "$TMUX" = "" ] && tmux
}

# If running from tty1 without an existing graphical session, start Hyprland.
if [[ -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" && $(tty 2>/dev/null) == "/dev/tty1" ]]; then
    $desktop
    start_tmux
fi

