#!/bin/zsh
# Copyright (c) 2018-2025 Jacob Peyron <jacob.peyron@gmail.com>
# Use of this source code is governed by an ICU License that can be found in the LICENSE file

readonly ENV_DIR=~/.config/zsh/env

if [ "$(uname)" = "Darwin" ]; then
    . "$ENV_DIR/macos.zsh"
fi

. "$ENV_DIR/env.zsh"
. "$ENV_DIR/path.zsh"
