#!/bin/zsh

# The infamous .zshrc
# This is to be kept as clean as possible.
# All configurations are put in separate
# units inside of ~/.config/zsh 
# (or whatever your XDG_CONFIG_HOME is).
#
# Author: Jacob Peyron
#

function exec_config_dir()
{
    zsh_dir=$XDG_CONFIG_HOME/zsh

    if [[ -d "$zsh_dir" ]] then
        scripts=($zsh_dir/*.zsh)
        foreach s in $scripts
            test -r "$s" && . "$s";
        end
    else
        echo Found no zsh script directory.
        echo Functionality of this shell is reduced.
   fi

}

exec_config_dir
