
function config_history()
{
    setopt inc_append_history   # immediately append history to history file
    setopt hist_ignore_dups     # ignore duplicate commands
    setopt hist_ignore_space    # ignore commands with leading space
}

function config_aliases() 
{
    alias -g ...='../..'
    alias -g ....='../../..'
    alias -g .....='../../../..'

    # I want colors for my standard operations.
    alias ls='ls --color=auto'
    alias lsl='ls -l'
    alias grep='grep --color=auto'

    alias ga='git add'
    alias gs='git status'
    alias gd='git diff'
    alias gl='git log --oneline --all --graph --decorate'
    alias gc='git commit --verbose'
}

function exec_sway()
{
    # If running trom tty1 start sway
    if [[ $(tty) == "/dev/tty1" ]]; then
        sway
        #exit 0
    fi
}

function post_shell_exec()
{
    exec_sway
}

function exec_config_dir()
{
    zsh_dir=$XDG_CONFIG_HOME/zsh

    if [[ -d "$zsh_dir" ]] then
        scripts=($zsh_dir/*.zsh)
        foreach s in $scripts
            test -r "$s" && . "$s";
        end
    else
        echo Found no zsh script directory.
        echo Functionality of this shell is reduced.
   fi

}

config_history
config_aliases

exec_config_dir
post_shell_exec
