#!/bin/zsh

# .zshrc
# This is the main configuration of zsh
#
# Author: Jacob Peyron
#

readonly ZSH_DIR=$XDG_CONFIG_HOME/zsh

. "$ZSH_DIR/init.zsh"
. "$ZSH_DIR/path.zsh"
. "$ZSH_DIR/alias.zsh"
. "$ZSH_DIR/prompt.zsh"
. "$ZSH_DIR/keyboard.zsh"
. "$ZSH_DIR/completion.zsh"

. "$ZSH_DIR/fzf-completion.zsh"

# When this is a problem, look into: {{ template "zshrc.extra" | nindent 0 }}
# . "$ZSH_DIR/wsl.zsh"
