#!/bin/bash

# THIS SCRIPT DIR
# INCLUDE COMMON
# refuse_root

# TODO: NO ROOT PLS

yay -Su --needed \
    linux-headers \
    wl-clipboard \
    nvidia-dkms \
    qt5-wayland \
    qt5ct \
    libva \
    libva-nvidia-driver-git \
    polkit-kde-agent \
    firefox \
    kitty \
    waybar \
    hyprland-nvidia \
    sift \
    wofi
